name: Build and Assert Assets Exists
description: Build the package and assert that file contents exist as we expect
runs:
  using: "composite"
  steps:
  - name: Build and Assert Output
    shell: bash
    run: |-
      echo '
        target: ember-resources/
        setup:
          run: pnpm build
          cwd: ./ember-resources
        expect: |
          dist/index.js
          dist/index.js.map
          declarations/index.d.ts

          
      ' >> assert-contents.config.yml
      npx assert-folder-contents

  - name: Upload dist assets to cache
    uses: actions/upload-artifact@v3
    with:
      name: dist
      path: ${{ env.dist }}
