name: Push dist

on:
  push:
    branches:
      - v6

jobs:
  push-dist:
    name: Push dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - uses: kategengler/put-built-npm-package-contents-on-branch@v2.0.0
        with:
          branch: dist-v6
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ember-resources
