name: Bundle Size

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  bundle-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: NullVoxPopuli/action-setup-pnpm@v2.1.0
      - name: Production Build (not shipped to npm)
        run: TERSER=1 pnpm build
      - name: Bundle the index.js
        run: node ./dev/estimate-bytes/bundle.js 
      - name: Run BundleMon
        run: pnpm bundlemon
