# This is how we can keep tabs on future typescript versions
# and if they are compatible with ember-resources
# without blocking PRs
# 
name: Weekly TypeScript 

on:
  workflow_dispatch:
  schedule:
    # Runs "At 03:00 on Sunday." (see https://crontab.guru)
    - cron: '0 3 * * 0'

jobs:
  install_dependencies:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3

  typecheck:
    name: '${{ matrix.typescript-scenario }}'
    runs-on: ubuntu-latest
    timeout-minutes: 2
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        typescript-scenario:
          - typescript@4.8
          - typescript@4.9
          - typescript@5.0
          - typescript@5.1
          - typescript@5.2
          - typescript@next

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm build
      - run: pnpm i -f # just in case
      - name: 'Change TS to ${{ matrix.typescript-scenario }}'
        run: 'pnpm add --save-dev ${{ matrix.typescript-scenario}}'
        working-directory: ./test-app
      - name: 'Type checking'

        run: |
          pnpm --filter test-app exec tsc -v;
          pnpm --filter test-app exec glint --version;
          pnpm --filter test-app exec glint;


